{% set version = '1.3.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-admiral
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/admiral_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/admiral/admiral_{{ version }}.tar.gz
  sha256: c0b37836b7709ee581caac20f626ac938de1263ce61baac56803ae3b1489a778

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-admiraldev >=1.3.1
    - r-cli >=3.6.2
    - r-dplyr >=1.0.5
    - r-hms >=0.5.3
    - r-lifecycle >=0.1.0
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-purrr >=0.3.3
    - r-rlang >=0.4.4
    - r-stringr >=1.4.0
    - r-tidyr >=1.0.2
    - r-tidyselect >=1.1.0
  run:
    - r-base
    - r-admiraldev >=1.3.1
    - r-cli >=3.6.2
    - r-dplyr >=1.0.5
    - r-hms >=0.5.3
    - r-lifecycle >=0.1.0
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-purrr >=0.3.3
    - r-rlang >=0.4.4
    - r-stringr >=1.4.0
    - r-tidyr >=1.0.2
    - r-tidyselect >=1.1.0

test:
  commands:
    - $R -e "library('admiral')"           # [not win]
    - "\"%R%\" -e \"library('admiral')\""  # [win]

about:
  home: https://pharmaverse.github.io/admiral/cran-release/, https://github.com/pharmaverse/admiral
  license: Apache-2.0
  summary: A toolbox for programming Clinical Data Interchange Standards Consortium (CDISC) compliant
    Analysis Data Model (ADaM) datasets in R. ADaM datasets are a mandatory part of
    any New Drug or Biologics License Application submitted to the United States Food
    and Drug Administration (FDA). Analysis derivations are implemented in accordance
    with the "Analysis Data Model Implementation Guide" (CDISC Analysis Data Model Team,
    2021, <https://www.cdisc.org/standards/foundational/adam>).
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
